name: om4labs
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - black
  - cartopy
  - cmocean
  - dask
  - gsw
  - intake-xarray
  - esmf=8.0.0
  - esmpy=8.0.0
  - matplotlib
  - mpich
  - netcdf4
  - numpy
  - numba
  - palettable
  - pyshp
  - pytest
  - regionmask
  - scipy
  - shapely
  - six
  - xarray
  - xesmf=0.6.2
  - xgcm
  - xhistogram
  - gsw
  - pip:
    - nc-time-axis>=1.3.1
    - git+https://github.com/jkrasting/cmip_basins.git
    - git+https://github.com/raphaeldussin/static_downsampler.git
    - git+https://github.com/raphaeldussin/xoverturning
    - git+https://github.com/jkrasting/xcompare.git
    - git+https://github.com/jkrasting/xwavelet.git
    - git+https://github.com/jkrasting/xcompare.git
