name: repro
channels:
  - conda-forge
dependencies:
  - python=3.8
  - black
  - cartopy
  - dask
  - intake-xarray
  - esmf=8.0.0
  - esmpy=8.0.0
  - matplotlib
  - netcdf4
  - numpy
  - palettable
  - pip
  - pip:
    - git+https://github.com/jkrasting/cmip_basins.git
    - git+https://github.com/raphaeldussin/static_downsampler.git
  - pyshp
  - pytest
  - regionmask
  - scipy
  - shapely
  - six
  - xarray
  - xesmf
  - xgcm
